travis:
  secure:
    BINSTAR_TOKEN: cIl9ir2/ztNrR3MXtV9eLnS4TsyfzLcVaAu5zxz35QMzGXn9hJW4tt9G2hmS5XhUCRViEiUM+uyblW+SRhLypYx9quKDsgSTc9SXCmbyPKrrAILspq0vazqbR63FLjjnZQE6EeHfHSJtzTzW6B+kniJBgFKqH348zKA2hJgTMK97vMMI9HjU/FmUZGyW0XQSvedmcNUNl4rHB7g+gkDZbV7yo41hfKPY8MqFBfjlXUbPveADnek4FurJNB2vSstc2yTWDdBNlKscuiQu8E6OZadqfbu7a/9pUjeS4smrWGpirO/O3TmtpnqvIYeKUTa9nIE64dyGCjNaO6gtOcpZOLLs8obvWWhkWR35twDcqnguxtp+cEa9FVklxbr1uFOa+3egmyJTIUKJZO50uJlWY+OHJfriZLUiXBpEjTt58G+9KwcVg+GR15GUCS5zALiw8jjZvM+ZMehghL4T5hV1b7wYBcBFRVzKNUszs/jG6TgkArgwqT4ajz1kNDNT2h+YryuQ2Em3ESRV5vgZmJBlgifhTtcQ+pIIieT2oHy3LbYc0aKi3FEYycwk+AbP6nOXo4IRjJRgSee7wWYYZ5O5pa9Azy/RmyiUtXaYpbsVjeGPF3uhqoX+82NySMFWbgqgROC2GaWxbfTzk9O9t0px9tnhpufkwgKNBqPAuiRjftI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
